### ISSUE TITLE
Thumbnail images

### ISSUE THREAD

**Issue by mehul-m-prajapati** [mehul-m-prajapati/mehul-m-prajapati.github.io#12]
Add post specific thumbnail images. It will appear when you share the content on social media 
Reference - [How to add thumbnail on Jekyll ?](https://stackoverflow.com/questions/39214375/how-can-you-get-thumbnails-for-jekyll-posts-when-the-post-has-no-images)

**Comment by felipebbarbosa** [comment]
Can I help with this?

**Comment by mehul-m-prajapati** [comment]
@felipebbarbosa Yes, please.
