### ISSUE TITLE
Resume

### ISSUE THREAD

**Issue by mehul-m-prajapati** [mehul-m-prajapati/mehul-m-prajapati.github.io#15]
Hi,

Add resume tab to download the latest CV from Resume repository.

Thanks,
Mehul

**Comment by brentrobbins** [comment]
@mehul-m-prajapati I would like to help, but where in your repo is your cv?

**Comment by mehul-m-prajapati** [comment]
Hi,

The resume link is: https://github.com/mehul-m-prajapati/Resume/blob/master/Resume.pdf

**Comment by brentrobbins** [comment]
Thanks @mehul-m-prajapati. Do you want the link to be titled something just like 'My Resume' or 'Resume' and do you want it to be the last link in your main nav?

**Comment by mehul-m-prajapati** [comment]
Yes. In main nav bar, after Categories tab, I want a title like **Resume**

**Comment by brentrobbins** [comment]
@mehul-m-prajapati Great. I just created a new PR with the Resume link to your main nav. #18

**Comment by mehul-m-prajapati** [comment]
Cool. Thanks @brentrobbins
