### ISSUE TITLE
Change font size and style

### ISSUE THREAD

**Issue by mehul-m-prajapati** [mehul-m-prajapati/mehul-m-prajapati.github.io#8]
Hi,

Font size of this [post](https://mehul-m-prajapati.github.io/compilation/Building-wireshark-using-visual-studio-13/), especially bullet text seems too big. Please make it small and also change the text style if possible.

Thanks,

**Comment by admir23** [comment]
hi @mehul-m-prajapati , can I work  on this?

Thanks!

**Comment by admir23** [comment]
Thanks,  can you assign it to me?

**Comment by mehul-m-prajapati** [comment]
I am not able to find your name in the assignment. You can work without it...

**Comment by admir23** [comment]
Thanks Mehul! I've made a PR for this issue..

**Comment by jessdan28** [comment]
Hello. I am a beginner and would like to try out this for my first pull request.  I would love any information on how to proceed. Thank you!

**Comment by Anupriya1729** [comment]
Hello sir, I'm a beginner and want to contribute.
Can you please assign it to me
